name: ogrow
description: Smart agriculture monitoring app

version: 1.4.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Animations
  lottie: ^2.6.0

  #url launcher
  url_launcher: ^6.2.1

  # Core Dependencies
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0

  # State Management
  provider: ^6.0.5
  shared_preferences: ^2.2.0

  # HTTP Networking
  http: ^1.1.0

  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Charts
  fl_chart: ^0.65.0

  # Internationalization
  intl: ^0.20.2

  # Image Processing
  image: ^4.1.3
  image_picker: ^1.0.4
  camera: ^0.10.5

  # Text-to-Speech
  flutter_tts: ^3.7.0

  # Permissions
  permission_handler: ^11.0.1

  # File Operations
  path_provider: ^2.1.1
  
  # UUID Generation
  uuid: ^4.1.0

  # Color Analysis
  palette_generator: ^0.3.3

  # ESP32 Real-Time
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/crop_grow.json
    - assets/animations/loading.json
    - assets/models/crop_prediction_model_ir9.onnx
